// lib/constants.ts
import { PaymentMethod, PropertyDetails, Service } from '@/types/type';

export const PROPERTY_DETAILS: PropertyDetails = {
  name: 'Hacienda B-25',
  resort: 'Puntacana Resort & Club',
  province: 'La Altagracia',
  municipality: 'Higuey',
  sector: 'Punta Cana',
  zipCode: '23000',
  country: 'Dominican Republic',
};

export const SERVICES: Service[] = [
  // Punta Cana Plan (Standard) Services
  {
    id: 'yoga-standard',
    name: 'Yoga',
    description: 'Relaxing yoga sessions at our beachfront pavilion',
    packageType: ['standard'],
    price: 50,
    duration: 1,
    available: true,
  },
  {
    id: 'bike-rentals',
    name: 'Bike Rentals',
    description: 'Explore the resort on our comfortable bicycles',
    packageType: ['standard'],
    price: 25,
    duration: 4,
    available: true,
  },
  {
    id: 'airport-transfers',
    name: 'Airport Transfers',
    description: 'Convenient transportation to and from Punta Cana Airport',
    packageType: ['standard'],
    price: 75,
    duration: 1,
    available: true,
  },
  {
    id: 'catamaran-trips',
    name: 'Catamaran Trips',
    description: 'Scenic sailing adventures along the coastline',
    packageType: ['standard'],
    price: 120,
    duration: 4,
    available: true,
  },
  {
    id: 'golf-cart-rentals',
    name: 'Golf Cart Rentals',
    description: 'Convenient transportation within the resort',
    packageType: ['standard'],
    price: 65,
    duration: 24,
    available: true,
  },
  {
    id: 'personal-training',
    name: 'Personal Training',
    description: 'One-on-one fitness sessions with certified trainers',
    packageType: ['standard'],
    price: 70,
    duration: 1,
    available: true,
  },
  {
    id: 'babysitter',
    name: 'Babysitter',
    description: 'Professional childcare services',
    packageType: ['standard'],
    price: 20,
    duration: 1,
    available: true,
  },
  {
    id: 'horseback-riding',
    name: 'Horseback Riding',
    description: 'Guided tours on horseback through scenic trails',
    packageType: ['standard'],
    price: 90,
    duration: 2,
    available: true,
  },
  {
    id: 'deep-sea-fishing',
    name: 'Deep-Sea Fishing',
    description: 'Exciting fishing excursions in the Caribbean Sea',
    packageType: ['standard'],
    price: 250,
    duration: 4,
    available: true,
  },
  {
    id: 'private-chef',
    name: 'Private Chef Service',
    description: 'Personalized culinary experiences in your accommodation',
    packageType: ['standard'],
    price: 200,
    duration: 3,
    available: true,
  },
  {
    id: 'custom-decorations',
    name: 'Custom Decorations',
    description: 'Special event decorations for celebrations',
    packageType: ['standard'],
    price: 150,
    duration: 0,
    available: true,
  },
  {
    id: 'adventure-excursions',
    name: 'Adventure Excursions',
    description: 'Thrilling activities and tours around Punta Cana',
    packageType: ['standard'],
    price: 110,
    duration: 6,
    available: true,
  },
  {
    id: 'karaoke',
    name: 'Private Karaoke Sessions',
    description: 'Fun karaoke setup in your accommodation',
    packageType: ['standard'],
    price: 120,
    duration: 3,
    available: true,
  },
  {
    id: 'live-music',
    name: 'Live Music Entertainment',
    description: 'Local musicians performing at your event',
    packageType: ['standard'],
    price: 300,
    duration: 3,
    available: true,
  },
  {
    id: 'grocery-shopping',
    name: 'Grocery Shopping Assistance',
    description: 'We shop for groceries and deliver to your accommodation',
    packageType: ['standard'],
    price: 50,
    duration: 0,
    available: true,
  },

  // Punta Cana Luxe (Premium) Services
  {
    id: 'luxe-yacht',
    name: 'Luxe Yacht',
    description: 'Private luxury yacht charter with crew',
    packageType: ['premium'],
    price: 1500,
    duration: 8,
    available: true,
  },
  {
    id: 'luxe-e-bikes',
    name: 'Luxe E-Bikes',
    description: 'Premium electric bikes for effortless exploration',
    packageType: ['premium'],
    price: 75,
    duration: 4,
    available: true,
  },
  {
    id: 'luxe-golf-cart',
    name: 'Luxe Golf Cart',
    description: 'Premium golf cart with extended features',
    packageType: ['premium'],
    price: 120,
    duration: 24,
    available: true,
  },
  {
    id: 'luxe-yoga',
    name: 'Luxe Yoga Sessions',
    description: 'Private beachfront yoga with premium amenities',
    packageType: ['premium'],
    price: 120,
    duration: 1.5,
    available: true,
  },
  {
    id: 'luxe-fitness',
    name: 'Luxe Fitness Sessions',
    description: 'Elite personal training with specialized equipment',
    packageType: ['premium'],
    price: 150,
    duration: 1.5,
    available: true,
  },
  {
    id: 'luxe-culinary',
    name: 'Luxe Culinary Service',
    description: 'Gourmet chef experience with premium ingredients',
    packageType: ['premium'],
    price: 500,
    duration: 4,
    available: true,
  },
  {
    id: 'luxe-masseuse',
    name: 'Luxe Masseuse Service',
    description: 'Premium spa treatments in your accommodation',
    packageType: ['premium'],
    price: 200,
    duration: 2,
    available: true,
  },
  {
    id: 'luxe-arrival',
    name: 'Luxe Arrival - SUV Service',
    description: 'Luxury SUV airport transfer with premium amenities',
    packageType: ['premium'],
    price: 150,
    duration: 1,
    available: true,
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 'azul',
    name: 'Azul',
    description:
      'Dominican payment processor accepting local and international cards',
    icon: 'credit-card',
    isAvailable: true,
  },
  {
    id: 'paypal',
    name: 'PayPal',
    description: 'Secure online payment service',
    icon: 'paypal',
    isAvailable: true,
  },
  {
    id: 'cardnet',
    name: 'CardNet',
    description: 'Local Dominican Republic payment network',
    icon: 'credit-card',
    isAvailable: true,
  },
  {
    id: 'tpago',
    name: 'tPago',
    description: 'Mobile payment service in Dominican Republic',
    icon: 'smartphone',
    isAvailable: true,
  },
  {
    id: 'visanet',
    name: 'VisaNet Dominicana',
    description: 'Process Visa card payments in Dominican Republic',
    icon: 'credit-card',
    isAvailable: true,
  },
  {
    id: 'bank-transfer',
    name: 'Bank Transfer',
    description: 'Direct bank transfer to our account',
    icon: 'bank',
    isAvailable: true,
  },
];
